"""
Game Client Simulator - Sends HTTP requests to Mantella server
Simulates the game sending commands to a running Mantella production service

How it works:
1. Game client sends requests to Mantella server via HTTP
2. For microphone input: 
   - Client sends empty string for player input
   - SERVER listens to the microphone (not the client)
   - Server transcribes speech and returns the text
3. Server generates NPC responses and synthesizes voice
4. Client receives voice files and plays them

This mimics the actual game-Mantella communication flow.
"""
import requests
import json
import logging
import csv
import soundfile as sf
import sounddevice as sd
from pathlib import Path
from src.http.communication_constants import communication_constants as comm_consts

# Configure basic logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S'
)


def play_audio(filename: str):
    """Play audio file synchronously"""
    try:
        data, samplerate = sf.read(filename)
        sd.play(data, samplerate)
        sd.wait()  # Wait until audio finishes
    except Exception as e:
        logging.error(f"Could not play audio: {e}")


class GameContextSimulator:
    """Simulates all game context data that Papyrus would gather."""
    
    # === DYNAMIC STATE (updated by actions) ===
    # NPCs currently following the player
    following_npcs: set = None
    # NPCs in combat with player
    hostile_npcs: set = None
    # Events generated by actions (consumed on next request)
    pending_action_events: list = None
    # Whether allowFollow MCM setting is enabled (simulated)
    allow_follow: bool = True
    # Whether allowInventory MCM setting is enabled (simulated)
    allow_inventory: bool = True
    
    def __init__(self):
        """Initialize dynamic state."""
        self.following_npcs = set()
        self.hostile_npcs = set()
        self.pending_action_events = []
        self._last_player_state_key = ""  # For state change tracking
        self.companion_faction_npcs = {
            # Simulated companion faction ranks (-1 = not in faction, 0+ = companion)
            "Dogmeat": 0,       # Companion
            "Codsworth": -1,    # Not yet a companion
            "Preston Garvey": -1,  # Not yet a companion (becomes one after quests)
            "Piper Wright": -1,
            "Nick Valentine": -1,
            "Sturges": -1,      # Never a companion
        }
    
    # Simulated companion faction membership (for testing follow logic)
    companion_faction_npcs: dict = None  # Maps NPC name -> faction rank (-1 = not companion)
    
    # MCM: allowActionAggro setting
    allow_aggro: bool = True
    # MCM: allowNPCsStayInPlace setting  
    allow_npcs_stay_in_place: bool = True
    
    def handle_action(self, action_id: str, action_args: dict) -> list:
        """
        Simulate game behavior for an action.
        Returns list of events that would be generated by the game.
        
        This mimics what MantellaConversation.psc TriggerCorrectCustomEvent does.
        """
        events = []
        sources = action_args.get("source", [])
        npc_name = sources[0] if sources else "Unknown"
        
        print(f"   [TRACE] ACTION: {action_id} from {npc_name}")
        
        if action_id == "mantella_reload_conversation":
            events.append("Reloading conversation...")
            print(f"   ✓ GAME: Reloading conversation")
            
        elif action_id == "mantella_end_conversation":
            events.append("Ending conversation...")
            print(f"   ✓ GAME: Conversation ended by NPC")
            
        elif action_id == "mantella_remove_character":
            events.append(f"{npc_name} left the conversation")
            print(f"   ✓ GAME: {npc_name} left conversation")
            
        elif action_id == "mantella_npc_offended":
            if self.allow_aggro:
                self.hostile_npcs.add(npc_name)
                self.DANGER_CONTEXT["in_combat"] = True
                self.PLAYER_STATE["in_combat"] = True
                events.append(f"{npc_name} is hostile!")
                print(f"   ⚔ GAME: {npc_name} is now hostile, combat started")
            else:
                print(f"   ✗ GAME: Aggro blocked (MCM: allowActionAggro=false)")
                print(f"   [TRACE] ACTION REJECTED: Aggro disabled in MCM")
                
        elif action_id == "mantella_npc_forgiven":
            events.append(f"{npc_name} calmed down")
            if npc_name in self.hostile_npcs:
                self.hostile_npcs.discard(npc_name)
                print(f"   ☮ GAME: {npc_name} is no longer hostile")
            if not self.hostile_npcs:
                self.DANGER_CONTEXT["in_combat"] = False
                self.PLAYER_STATE["in_combat"] = False
                events.append("Combat has ended")
                
        elif action_id == "mantella_npc_follow":
            # Simulate MantellaConversation.psc follow logic exactly
            if not self.allow_follow:
                print(f"   ✗ GAME: Follow blocked (MCM: allowFollow=false)")
                print(f"   [TRACE] ACTION REJECTED: Follow disabled in MCM")
            else:
                # Check companion faction membership
                faction_rank = self.companion_faction_npcs.get(npc_name, -1) if self.companion_faction_npcs else -1
                is_companion = faction_rank >= 0
                
                if is_companion and not self.allow_npcs_stay_in_place:
                    print(f"   ✗ GAME: {npc_name} is already a companion")
                    print(f"   [TRACE] ACTION REJECTED: {npc_name} already in CompanionFaction (rank={faction_rank}), allowNPCsStayInPlace=false")
                else:
                    # Success
                    self.following_npcs.add(npc_name)
                    events.append(f"{npc_name} is following")
                    print(f"   ✓ GAME: {npc_name} is following")
                    print(f"   [TRACE] ACTION SUCCESS: {npc_name} now following")
                    
        elif action_id == "mantella_npc_inventory":
            if self.allow_inventory:
                events.append(f"{npc_name} inventory opened")
                print(f"   ✓ GAME: {npc_name} inventory opened")
            else:
                print(f"   ✗ GAME: Inventory blocked (MCM: allowActionInventory=false)")
                print(f"   [TRACE] ACTION REJECTED: Inventory disabled in MCM")
        
        elif action_id == "mantella_npc_unfollow":
            if npc_name in self.following_npcs:
                self.following_npcs.discard(npc_name)
                events.append(f"{npc_name} stopped following")
                print(f"   ✓ GAME: {npc_name} stopped following")
                print(f"   [TRACE] ACTION SUCCESS: {npc_name} stopped following")
            else:
                print(f"   ℹ GAME: {npc_name} was not following")
        
        elif action_id == "mantella_npc_wait":
            events.append(f"{npc_name} will wait")
            print(f"   ✓ GAME: {npc_name} will wait")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} waiting")
        
        elif action_id == "mantella_npc_moveto":
            target = action_args.get("target", "unknown")
            events.append(f"{npc_name} is moving towards {target}")
            print(f"   ✓ GAME: {npc_name} moving towards {target}")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} moving to {target}")
        
        elif action_id == "mantella_npc_loot":
            mode = action_args.get("mode", "any")
            events.append(f"{npc_name} will scavenge {mode} items")
            print(f"   ✓ GAME: {npc_name} scavenging {mode} items")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} looting {mode}")
        
        elif action_id == "mantella_heal_me":
            events.append(f"{npc_name} will heal the player")
            print(f"   💉 GAME: {npc_name} healing player with stimpak")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} healing player")
        
        elif action_id == "mantella_npc_use_item_on_target":
            target = action_args.get("target", "unknown")
            item_type = action_args.get("mode", "stimpak")
            events.append(f"{npc_name} using {item_type} on {target}")
            print(f"   💉 GAME: {npc_name} using {item_type} on {target}")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} using {item_type} on {target}")
        
        elif action_id == "mantella_npc_attack_other_npc":
            target = action_args.get("target", "unknown")
            events.append(f"{npc_name} is attacking {target}")
            self.DANGER_CONTEXT["in_combat"] = True
            self.PLAYER_STATE["in_combat"] = True
            print(f"   ⚔ GAME: {npc_name} attacking {target}")
            print(f"   [TRACE] ACTION SUCCESS: {npc_name} attacking {target}")
                
        else:
            print(f"   ℹ GAME: Action '{action_id}' acknowledged (no special handling)")
        
        # Store events for next context update
        self.pending_action_events.extend(events)
        return events
    
    def get_and_clear_action_events(self) -> list:
        """Get events generated by actions and clear them."""
        events = self.pending_action_events.copy()
        self.pending_action_events.clear()
        return events
    
    # Simulated quest database - maps decimal FormID to (quest_name, status, stage, locations)
    # Based on actual game output for Preston Garvey
    # locations = list of "LocationName (AliasName)" strings for radiant quests (via Lighthouse extender)
    SIMULATED_QUESTS = {
        # Preston Garvey / Minutemen main quests
        1703964: ("When Freedom Calls", "completed", 0, []),  # 0x001A0038
        238679: ("The First Step", "not_started", 0, []),     # 0x0003A467
        726866: ("Taking Independence", "not_started", 0, []), # 0x000B1752
        1270569: ("Old Guns", "not_started", 0, []),          # 0x00136399
        1099338: ("Defend the Castle", "not_started", 0, []), # 0x0010C64A (note: game shows "Defend The Castle")
        776964: ("Form Ranks", "not_started", 0, []),         # 0x000BDA44
        1160046: ("Sanctuary", "completed", 0, []),           # 0x0011B06E
        1495094: ("Inside Job", "not_started", 0, []),        # 0x0016CF26
        658758: ("The Nuclear Option", "not_started", 0, []), # 0x000A0D46 (Minutemen ending)
        1082598: ("With Our Powers Combined", "not_started", 0, []), # 0x00108966
        527718: ("Out of the Fire", "not_started", 0, []),    # 0x00080D66
        1245511: ("Troubled Waters", "not_started", 0, []),   # 0x00130147
        
        # Preston Garvey radiant quests (with <Alias> placeholders and resolved locations with alias names)
        622902: ("Raider Troubles at <Alias=ActualLocation>", "running", 50, ["Outpost Zimonja (ActualLocation)", "BADTFL Regional Office (RaiderDungeon)"]),  # 0x00098136
        622903: ("Clearing the Way for <Alias=ActualLocation>", "not_started", 0, []),
        622904: ("Defend <Alias=ActualLocation>", "not_started", 0, []),
        622905: ("Defend the artillery at <Alias=ActualLocation>", "not_started", 0, []),
        622906: ("Ghoul Problem at <Alias=ActualLocation>", "not_started", 0, []),
        622907: ("<Alias=ActualLocation>: Greenskins", "not_started", 0, []),  # Super Mutant Troubles
        622908: ("Kidnapping at <Alias=ActualLocation>", "not_started", 0, []),
        622909: ("Resettle Refugees at <Alias=HostileWorkshopLocation>", "not_started", 0, []),
        622910: ("Rogue Courser at <Alias=Dungeon>", "not_started", 0, []),
        622911: ("Stop the Raiding at <Alias=ActualLocation>", "not_started", 0, []),
        622912: ("Taking Point: <Alias=HostileWorkshopLocation>", "not_started", 0, []),
        
        # Nick Valentine quests
        106457: ("Long Time Coming", "running", 100, []),
        
        # General quests
        106969: ("Out of Time", "completed", 0),
    }
    
    # Simulated player state (aligned with unified GetPlayerStateContext in Papyrus)
    PLAYER_STATE = {
        "level": 15,
        "weapon": "10mm Pistol",
        "weapon_drawn": True,
        "power_armor": False,
        "overencumbered": False,
        "sneaking": False,
        "sneaking_detected": False,
        "bleeding_out": False,
        "in_combat": False,
        "searching": False,
        "health_percent": 0.85,  # 0.0-1.0 (like Papyrus RadFactoredHealth)
        "rad_percent": 0.0       # 0.0-1.0 (like Papyrus RadiationPercent)
    }
    
    # State change tracking (like _lastPlayerStateKey in Papyrus)
    _last_player_state_key: str = ""
    
    # Simulated nearby NPCs - new format with key-value pairs
    # Format: name=X;distance=Y;faction=Z;activity=A;health=H[;weapon=W][;armed=A]
    NEARBY_NPCS = [
        {"name": "Dogmeat", "distance": 985, "faction": "Companion", "activity": "Idle", "health": "healthy", "weapon": "drawn"},
        {"name": "Sturges", "distance": 1722, "faction": "Settler", "activity": "Idle", "health": "healthy", "armed": "Pipe"},
        {"name": "Jun Long", "distance": 1645, "faction": "Settler", "activity": "Idle", "health": "healthy", "armed": "Pipe"},
        {"name": "Marcy Long", "distance": 2249, "faction": "Settler", "activity": "Idle", "health": "healthy", "armed": "Pipe"},
        {"name": "Mama Murphy", "distance": 3592, "faction": "Settler", "activity": "sitting", "health": "healthy"},
        {"name": "Codsworth", "distance": 2660, "faction": "Settler", "activity": "Idle", "health": "healthy"},
    ]
    
    # Simulated danger context
    DANGER_CONTEXT = {
        "hostiles": 0,
        "in_combat": False,
        "dead_bodies": 0
    }
    
    # Simulated settlement context
    SETTLEMENT_CONTEXT = {
        "population": 6,
        "is_settlement": True
    }
    
    # Simulated environment context
    ENVIRONMENT_CONTEXT = {
        "radiation_level": 0,  # 0=none, 1=moderate, 2=high
        "player_health_critical": False
    }
    
    # Simulated player active effects
    PLAYER_EFFECTS = [
        "Fortify Carry Weight"
    ]
    
    # Simulated NPC roles for conversation participants
    NPC_ROLES = {
        "Preston Garvey": {
            "companion": True,
            "relationship": 3,  # Ally
            "faction": "minutemen",
            "essential": True
        },
        "Piper Wright": {
            "companion": True,
            "relationship": 2,  # Confidant
            "faction": "companion",
            "essential": True
        },
        "Nick Valentine": {
            "companion": True,
            "relationship": 2,
            "faction": "companion",
            "essential": True
        },
        "Sturges": {
            "companion": False,
            "relationship": 1,  # Friend
            "faction": "settler",
            "essential": False
        }
    }
    
    # Simulated location
    LOCATION = {
        "name": "Sanctuary Hills",
        "type": "settlement",
        "interior": False
    }
    
    def get_player_state_string(self) -> str:
        """Generate player state string like Papyrus GetPlayerStateContext().
        Format: level:X|weapon:Y|weapon_drawn|power_armor|overencumbered|sneaking|bleeding_out|in_combat|heavily_wounded|irradiated
        """
        parts = [f"level:{self.PLAYER_STATE['level']}"]
        
        if self.PLAYER_STATE["weapon"]:
            parts.append(f"weapon:{self.PLAYER_STATE['weapon']}")
        if self.PLAYER_STATE["weapon_drawn"]:
            parts.append("weapon_drawn")
        else:
            parts.append("weapon_holstered")
        if self.PLAYER_STATE["power_armor"]:
            parts.append("power_armor")
        if self.PLAYER_STATE["overencumbered"]:
            parts.append("overencumbered")
        if self.PLAYER_STATE["sneaking"]:
            if self.PLAYER_STATE["sneaking_detected"]:
                parts.append("sneaking_detected")
            else:
                parts.append("sneaking")
        if self.PLAYER_STATE["bleeding_out"]:
            parts.append("bleeding_out")
        if self.PLAYER_STATE["in_combat"]:
            parts.append("in_combat")
        elif self.PLAYER_STATE["searching"]:
            parts.append("searching")
        
        # Health status (matching Papyrus thresholds)
        health = self.PLAYER_STATE["health_percent"]
        if health < 0.4:
            parts.append("heavily_wounded")
        elif health < 0.7:
            parts.append("moderately_wounded")
        elif health < 0.9:
            parts.append("lightly_wounded")
        
        # Radiation status (matching Papyrus thresholds)
        rad = self.PLAYER_STATE["rad_percent"]
        if rad > 0.6:
            parts.append("heavily_irradiated")
        elif rad > 0.3:
            parts.append("moderately_irradiated")
        elif rad > 0.15:
            parts.append("lightly_irradiated")
        
        return "|".join(parts)
    
    def get_player_state_as_event(self) -> str:
        """Generate natural language player state event like Papyrus GetPlayerStateAsEvent().
        Returns empty string if state hasn't changed significantly.
        Format: "The player is sneaking, heavily wounded & heavily irradiated"
        """
        state_items = []
        
        # Build list of significant state items
        if self.PLAYER_STATE["power_armor"]:
            state_items.append("in power armor")
        if self.PLAYER_STATE["overencumbered"]:
            state_items.append("overencumbered")
        if self.PLAYER_STATE["sneaking"]:
            state_items.append("sneaking")
        if self.PLAYER_STATE["bleeding_out"]:
            state_items.append("bleeding out")
        
        # Health status
        health = self.PLAYER_STATE["health_percent"]
        if health < 0.4:
            state_items.append("heavily wounded")
        elif health < 0.7:
            state_items.append("moderately wounded")
        elif health < 0.9:
            state_items.append("lightly wounded")
        
        # Radiation status
        rad = self.PLAYER_STATE["rad_percent"]
        if rad > 0.6:
            state_items.append("heavily irradiated")
        elif rad > 0.3:
            state_items.append("moderately irradiated")
        elif rad > 0.15:
            state_items.append("lightly irradiated")
        
        # Combat state
        if self.PLAYER_STATE["in_combat"]:
            state_items.append("in combat")
        elif self.PLAYER_STATE["searching"]:
            state_items.append("alert and searching")
        
        # Build state key for change detection
        state_key = "".join(state_items)
        
        # Check if state changed
        if state_key == self._last_player_state_key:
            return ""  # No change
        self._last_player_state_key = state_key
        
        # Build natural language result
        if not state_items:
            return ""
        
        if len(state_items) == 1:
            return f"The player is {state_items[0]}"
        elif len(state_items) == 2:
            return f"The player is {state_items[0]} & {state_items[1]}"
        else:
            return f"The player is {', '.join(state_items[:-1])} & {state_items[-1]}"
    
    def check_and_log_state_changes(self) -> list:
        """Check for player state changes and return events if changed.
        Mirrors Papyrus CheckAndLogPlayerStateChanges().
        """
        events = []
        state_event = self.get_player_state_as_event()
        if state_event:
            events.append(state_event)
            print(f"   [STATE] Player state changed: {state_event}")
        return events
    
    def reset_player_state_tracking(self):
        """Reset state tracking at conversation start.
        Mirrors Papyrus ResetPlayerStateTracking().
        """
        self._last_player_state_key = ""
    
    def get_nearby_npcs_string(self) -> str:
        """Generate nearby NPCs string like Papyrus would.
        New format: name=X;distance=Y;faction=Z;activity=A;health=H|name=X2;...
        """
        entries = []
        for npc in self.NEARBY_NPCS:
            parts = [
                f"name={npc['name']}",
                f"distance={npc['distance']}",
                f"faction={npc['faction']}",
                f"activity={npc['activity']}",
                f"health={npc['health']}"
            ]
            if "weapon" in npc:
                parts.append(f"weapon={npc['weapon']}")
            if "armed" in npc:
                parts.append(f"armed={npc['armed']}")
            entries.append(";".join(parts))
        return "|".join(entries)
    
    def get_danger_context_string(self) -> str:
        """Generate danger context string.
        Format: hostiles:X|in_combat|dead_bodies:Y
        """
        parts = [f"hostiles:{self.DANGER_CONTEXT['hostiles']}"]
        if self.DANGER_CONTEXT["in_combat"]:
            parts.append("in_combat")
        if self.DANGER_CONTEXT["dead_bodies"] > 0:
            parts.append(f"dead_bodies:{self.DANGER_CONTEXT['dead_bodies']}")
        return "|".join(parts)
    
    def get_settlement_context_string(self) -> str:
        """Generate settlement context string.
        Format: population:X
        """
        if not self.SETTLEMENT_CONTEXT["is_settlement"]:
            return ""
        return f"population:{self.SETTLEMENT_CONTEXT['population']}"
    
    def get_environment_context_string(self) -> str:
        """Generate environment context string.
        Format: radiation_high|health_low
        """
        parts = []
        if self.ENVIRONMENT_CONTEXT["radiation_level"] == 2:
            parts.append("radiation_high")
        elif self.ENVIRONMENT_CONTEXT["radiation_level"] == 1:
            parts.append("radiation_moderate")
        if self.ENVIRONMENT_CONTEXT["player_health_critical"]:
            parts.append("health_low")
        return "|".join(parts) if parts else ""
    
    def get_player_effects_string(self) -> str:
        """Generate player effects string.
        Format: Effect1|Effect2|Effect3
        """
        return "|".join(self.PLAYER_EFFECTS)
    
    def get_npc_role_string(self, npc_name: str) -> str:
        """Generate NPC role string for a specific NPC."""
        if npc_name not in self.NPC_ROLES:
            return "relationship:0"
        
        role = self.NPC_ROLES[npc_name]
        parts = []
        
        if role.get("companion"):
            parts.append("companion")
        
        parts.append(f"relationship:{role.get('relationship', 0)}")
        
        if role.get("faction"):
            parts.append(f"faction:{role['faction']}")
        
        if role.get("essential"):
            parts.append("essential")
        
        return "|".join(parts)
    
    def get_location_string(self) -> str:
        """Generate location string like Papyrus would."""
        parts = []
        if self.LOCATION.get("name"):
            parts.append(f"name:{self.LOCATION['name']}")
        
        if self.LOCATION.get("interior"):
            parts.append("interior")
        else:
            parts.append("exterior")
        
        return "|".join(parts)
    
    def simulate_quest_check(self, quest_ids: list[int]) -> str:
        """Simulate Papyrus CheckQuestsFromFormIDs function.
        
        Format: QuestName:status[:stage][:Location1~Location2]
        Matches actual game output with Lighthouse Papyrus Extender location data.
        """
        if not quest_ids:
            return ""
        
        results = []
        for form_id in quest_ids:
            if form_id in self.SIMULATED_QUESTS:
                quest_data = self.SIMULATED_QUESTS[form_id]
                name = quest_data[0]
                status = quest_data[1]
                stage = quest_data[2]
                locations = quest_data[3] if len(quest_data) > 3 else []
                
                # Build quest entry: Name:Status[:Stage][:Location1~Location2]
                if status == "completed":
                    entry = f"{name}:completed"
                elif status == "running":
                    entry = f"{name}:running:{stage}"
                    # Add locations for running radiant quests (via Lighthouse extender)
                    if locations:
                        entry += ":" + "~".join(locations)
                else:
                    entry = f"{name}:not_started"
                
                results.append(entry)
        
        return "|".join(results)
    
    def get_full_context(self, npc_name: str, quest_ids: list[int] | None = None) -> dict:
        """Get all simulated game context values."""
        context = {
            # Player state
            comm_consts.KEY_CONTEXT_PLAYER_STATE: self.get_player_state_string(),
            "mantella_player_health_percent": self.PLAYER_STATE["health_percent"],
            "mantella_player_rad_percent": self.PLAYER_STATE["rad_percent"],
            
            # Nearby NPCs (new format)
            comm_consts.KEY_CONTEXT_NEARBY_NPCS: self.get_nearby_npcs_string(),
            
            # NPC role
            comm_consts.KEY_CONTEXT_NPC_ROLE: self.get_npc_role_string(npc_name),
            
            # Location
            comm_consts.KEY_CONTEXT_LOCATION_TYPE: self.get_location_string(),
            
            # New context types
            comm_consts.KEY_CONTEXT_DANGER: self.get_danger_context_string(),
            comm_consts.KEY_CONTEXT_SETTLEMENT: self.get_settlement_context_string(),
            comm_consts.KEY_CONTEXT_ENVIRONMENT: self.get_environment_context_string(),
            comm_consts.KEY_CONTEXT_PLAYER_EFFECTS: self.get_player_effects_string(),
        }
        
        # Quest context if quest IDs provided
        if quest_ids:
            quest_string = self.simulate_quest_check(quest_ids)
            if quest_string:
                context[comm_consts.KEY_CONTEXT_NPC_QUESTS] = quest_string
                logging.info(f"🎮 Quest context: {quest_string}")
        
        return context


class GameClientSimulator:
    """Simulates a game client sending HTTP requests to Mantella server"""
    
    def __init__(self, server_url: str = "http://localhost:4999"):
        """Initialize the game client simulator
        
        Args:
            server_url: Base URL of the Mantella server (default: http://localhost:4999)
        """
        self.server_url = f"{server_url}/mantella"
        self.session = requests.Session()
        self.turn_counter = 0
        self.pending_quest_context = ""  # Simulates Papyrus _pendingQuestContext
        self.game_context = GameContextSimulator()
        self.current_npc_name = ""
        self.pending_quest_ids: list[int] = []
        # Cached context values (like Papyrus _cached_* variables)
        self._cached_player_state: str = ""
        self._cached_nearby_npcs: str = ""
        self._cached_npc_role: str = ""
        self._cached_location_type: str = ""
        self._cached_danger: str = ""
        
    def send_request(self, request_data: dict) -> dict:
        """Send an HTTP POST request to Mantella server
        
        Args:
            request_data: The request payload to send
            
        Returns:
            The server's response as a dictionary
        """
        try:
            logging.debug(f"Sending request: {json.dumps(request_data, indent=2)}")
            response = self.session.post(
                self.server_url,
                json=request_data,
                timeout=120  # 2 minutes for mic input + STT processing
            )
            response.raise_for_status()
            response_data = response.json()
            logging.debug(f"Received response: {json.dumps(response_data, indent=2)}")
            return response_data
        except requests.exceptions.ConnectionError:
            logging.error("❌ Could not connect to Mantella server. Is it running?")
            raise
        except requests.exceptions.Timeout:
            logging.error("❌ Request timed out")
            raise
        except Exception as e:
            logging.error(f"❌ Request failed: {e}")
            raise
    
    def initialize(self) -> dict:
        """Send initialization request"""
        logging.info("Sending INIT request...")
        request = {
            comm_consts.KEY_REQUESTTYPE: comm_consts.KEY_REQUESTTYPE_INIT
        }
        return self.send_request(request)
    
    def start_conversation(self, npc_data: dict, use_microphone: bool = False) -> dict:
        """Send start conversation request
        
        Args:
            npc_data: Dictionary containing NPC information from CSV
            use_microphone: Whether to use microphone input (server-side) or text input
            
        Returns:
            Server response
        """
        self.current_npc_name = npc_data['name']
        
        # Parse NPC data
        base_id = npc_data['base_id']
        try:
            base_id = int(base_id, 16)
        except:
            base_id = int(base_id)
        
        gender = 0
        if str(npc_data.get('gender', '')).lower() in ['female', '1', 'f']:
            gender = 1
        
        race = npc_data.get('race', 'Human')
        if not race.startswith('<') and not race.endswith('Race>'):
            race = f"<{race}Race>"
        
        # Choose input type based on config
        input_type = comm_consts.KEY_INPUTTYPE_MIC if use_microphone else comm_consts.KEY_INPUTTYPE_TEXT
        
        request = {
            comm_consts.KEY_REQUESTTYPE: comm_consts.KEY_REQUESTTYPE_STARTCONVERSATION,
            comm_consts.KEY_STARTCONVERSATION_WORLDID: "SanctuaryHillsWorld",
            comm_consts.KEY_INPUTTYPE: input_type,
            comm_consts.KEY_ACTORS: [
                {
                    comm_consts.KEY_ACTOR_BASEID: base_id,
                    comm_consts.KEY_ACTOR_REFID: base_id,
                    comm_consts.KEY_ACTOR_NAME: npc_data['name'],
                    comm_consts.KEY_ACTOR_GENDER: gender,
                    comm_consts.KEY_ACTOR_RACE: race,
                    comm_consts.KEY_ACTOR_VOICETYPE: f"<{npc_data.get('fallout4_voice_folder', 'MaleBoston')}>",
                    comm_consts.KEY_ACTOR_ISINCOMBAT: False,
                    comm_consts.KEY_ACTOR_ISENEMY: False,
                    comm_consts.KEY_ACTOR_RELATIONSHIPRANK: 0,
                    comm_consts.KEY_ACTOR_ISPLAYER: False,
                    comm_consts.KEY_ACTOR_CUSTOMVALUES: {},
                    comm_consts.KEY_ACTOR_EQUIPMENT: {}
                },
                {
                    comm_consts.KEY_ACTOR_BASEID: 7,
                    comm_consts.KEY_ACTOR_REFID: 7,
                    comm_consts.KEY_ACTOR_NAME: "Player",
                    comm_consts.KEY_ACTOR_GENDER: 0,
                    comm_consts.KEY_ACTOR_RACE: "<HumanRace>",
                    comm_consts.KEY_ACTOR_VOICETYPE: "<MaleBoston>",
                    comm_consts.KEY_ACTOR_ISINCOMBAT: False,
                    comm_consts.KEY_ACTOR_ISENEMY: False,
                    comm_consts.KEY_ACTOR_RELATIONSHIPRANK: 0,
                    comm_consts.KEY_ACTOR_ISPLAYER: True,
                    comm_consts.KEY_ACTOR_CUSTOMVALUES: {},
                    comm_consts.KEY_ACTOR_EQUIPMENT: {}
                }
            ],
            comm_consts.KEY_CONTEXT: {
                comm_consts.KEY_CONTEXT_LOCATION: "Sanctuary Hills",
                comm_consts.KEY_CONTEXT_TIME: 12,
                comm_consts.KEY_CONTEXT_INGAMEEVENTS: [],
                comm_consts.KEY_CONTEXT_WEATHER: "Clear",
                comm_consts.KEY_CONTEXT_CUSTOMVALUES: {}
            }
        }
        
        # Reset player state tracking at conversation start (like Papyrus ResetPlayerStateTracking)
        self.game_context.reset_player_state_tracking()
        
        # Cache expensive context values (like Papyrus CacheExpensiveContext)
        full_ctx = self.game_context.get_full_context(npc_data['name'], None)
        self._cached_player_state = full_ctx.get(comm_consts.KEY_CONTEXT_PLAYER_LEVEL, "")
        self._cached_nearby_npcs = full_ctx.get(comm_consts.KEY_CONTEXT_NEARBY_NPCS, "")
        self._cached_npc_role = full_ctx.get(comm_consts.KEY_CONTEXT_NPC_ROLE, "")
        self._cached_location_type = full_ctx.get(comm_consts.KEY_CONTEXT_LOCATION_TYPE, "")
        self._cached_danger = full_ctx.get(comm_consts.KEY_CONTEXT_DANGER, "")
        
        # Add cached + fresh values to custom context (like BuildCustomContextValues)
        request[comm_consts.KEY_CONTEXT][comm_consts.KEY_CONTEXT_CUSTOMVALUES] = self._build_custom_context_values()
        
        logging.info("Sending START CONVERSATION request...")
        return self.send_request(request)
    
    def _build_custom_context_values(self) -> dict:
        """Combine cached + fresh values (like Papyrus BuildCustomContextValues)"""
        ctx = {}
        # Fresh values
        ctx[comm_consts.KEY_CONTEXT_CUSTOMVALUES_PLAYERHEALTH] = self.game_context.player_health
        ctx[comm_consts.KEY_CONTEXT_CUSTOMVALUES_PLAYERRAD] = self.game_context.player_radiation
        # Cached values
        if self._cached_player_state:
            ctx[comm_consts.KEY_CONTEXT_PLAYER_LEVEL] = self._cached_player_state
        if self._cached_nearby_npcs:
            ctx[comm_consts.KEY_CONTEXT_NEARBY_NPCS] = self._cached_nearby_npcs
        if self._cached_npc_role:
            ctx[comm_consts.KEY_CONTEXT_NPC_ROLE] = self._cached_npc_role
        if self._cached_location_type:
            ctx[comm_consts.KEY_CONTEXT_LOCATION_TYPE] = self._cached_location_type
        if self._cached_danger:
            ctx[comm_consts.KEY_CONTEXT_DANGER] = self._cached_danger
        if self.pending_quest_context:
            ctx[comm_consts.KEY_CONTEXT_NPC_QUESTS] = self.pending_quest_context
        return ctx
    
    def continue_conversation(self, context: dict | None = None) -> dict:
        """Send continue conversation request
        
        Args:
            context: Optional context to include (events, location, etc.)
            
        Returns:
            Server response
        """
        if context is None:
            context = {
                comm_consts.KEY_CONTEXT_LOCATION: "Sanctuary Hills",
                comm_consts.KEY_CONTEXT_TIME: 12,
                comm_consts.KEY_CONTEXT_INGAMEEVENTS: [],
                comm_consts.KEY_CONTEXT_WEATHER: "Clear",
            }
        
        # Add cached + fresh values (like BuildCustomContextValues)
        context[comm_consts.KEY_CONTEXT_CUSTOMVALUES] = self._build_custom_context_values()
        
        request = {
            comm_consts.KEY_REQUESTTYPE: comm_consts.KEY_REQUESTTYPE_CONTINUECONVERSATION,
            comm_consts.KEY_CONTINUECONVERSATION_TOPICINFOFILE: 1,
            comm_consts.KEY_CONTEXT: context
        }
        
        return self.send_request(request)
    
    def player_input(self, player_text: str, context: dict | None = None) -> dict:
        """Send player input request
        
        Args:
            player_text: The text the player said
            context: Optional context to include
            
        Returns:
            Server response
        """
        if context is None:
            context = {
                comm_consts.KEY_CONTEXT_LOCATION: "Sanctuary Hills",
                comm_consts.KEY_CONTEXT_TIME: 12,
                comm_consts.KEY_CONTEXT_INGAMEEVENTS: [],
                comm_consts.KEY_CONTEXT_WEATHER: "Clear",
            }
        
        # Check for player state changes when there's actual input
        # (like Papyrus CheckAndLogPlayerStateChanges in sendRequestForPlayerInput)
        if player_text:
            state_events = self.game_context.check_and_log_state_changes()
            if state_events:
                if comm_consts.KEY_CONTEXT_INGAMEEVENTS not in context:
                    context[comm_consts.KEY_CONTEXT_INGAMEEVENTS] = []
                context[comm_consts.KEY_CONTEXT_INGAMEEVENTS].extend(state_events)
        
        # Add cached + fresh values (like BuildCustomContextValues)
        context[comm_consts.KEY_CONTEXT_CUSTOMVALUES] = self._build_custom_context_values()
        
        request = {
            comm_consts.KEY_REQUESTTYPE: comm_consts.KEY_REQUESTTYPE_PLAYERINPUT,
            comm_consts.KEY_REQUESTTYPE_PLAYERINPUT: player_text,
            comm_consts.KEY_CONTEXT: context
        }
        
        logging.info(f"Sending PLAYER INPUT: '{player_text}'")
        return self.send_request(request)
    
    def end_conversation(self) -> dict:
        """Send end conversation request"""
        request = {
            comm_consts.KEY_REQUESTTYPE: comm_consts.KEY_REQUESTTYPE_ENDCONVERSATION
        }
        
        logging.info("Sending END CONVERSATION request...")
        return self.send_request(request)
    
    def process_start_response(self, response: dict) -> None:
        """Process start_conversation_completed response like Papyrus does
        
        Extracts quest IDs and stores them for later use.
        """
        if comm_consts.KEY_QUEST_IDS_TO_CHECK in response:
            quest_ids = response[comm_consts.KEY_QUEST_IDS_TO_CHECK]
            logging.info(f"📋 Received quest FormIDs to check: {quest_ids}")
            self.pending_quest_ids = quest_ids
        else:
            logging.info("📋 No quest IDs received from server")
            self.pending_quest_ids = []


def select_npc() -> dict:
    """Let user select an NPC from the CSV file"""
    npc_file = 'data/Fallout4/fallout4_characters.csv'
    npcs = []
    
    with open(npc_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['name'] and row['base_id']:
                npcs.append(row)
    
    print(f"\n📋 Found {len(npcs)} NPCs. Showing first 10:")
    for i, npc in enumerate(npcs[:10], 1):
        print(f"  {i}. {npc['name']}")
    
    choice = input(f"\n👉 Enter number (1-10), name to search, or Enter for first: ").strip()
    
    if not choice:
        selected = npcs[0]
    elif choice.isdigit():
        idx = int(choice) - 1
        selected = npcs[idx]
    else:
        # Search by name (case-insensitive)
        matches = [n for n in npcs if choice.lower() in n['name'].lower()]
        if not matches:
            print(f"❌ No NPC found matching '{choice}'")
            return select_npc()
        elif len(matches) == 1:
            selected = matches[0]
        else:
            print(f"\n🔍 Found {len(matches)} matches:")
            for i, npc in enumerate(matches[:10], 1):
                print(f"  {i}. {npc['name']}")
            sub_choice = input(f"\n👉 Select (1-{min(10, len(matches))}): ").strip()
            idx = int(sub_choice) - 1 if sub_choice else 0
            selected = matches[idx]
    
    print(f"\n✓ Selected: {selected['name']}\n")
    return selected


def get_test_events(turn: int, npc_name: str) -> list[str]:
    """Generate scenario-based test events for different turns.
    
    These events simulate what might happen in the game world.
    Action-generated events are handled separately in the main loop.
    """
    scenarios = {
        # Turn 3: Item pickup events
        3: [f"The player picked up a Stimpak", 
            f"The player equipped Leather Armor"],
        # Turn 6: Combat starting
        6: [f"A Raider appeared nearby",
            f"{npc_name} drew their weapon"],
        # Turn 9: Combat escalating  
        9: [f"The player is being attacked by Raiders",
            f"The player entered combat",
            f"{npc_name} is in combat"],
        # Turn 12: Post-combat
        12: [f"The player killed a Raider",
             f"Combat has ended",
             f"The player picked up a Legendary Weapon"],
        # Turn 15: Location change
        15: [f"The location is now Diamond City"],
        # Turn 18: NPC interaction
        18: [f"{npc_name} sat down",
             f"The player is crouching"],
    }
    return scenarios.get(turn, [])


def main():
    print("="*60)
    print("Game Client Simulator - Sends requests to Mantella server")
    print("="*60)
    
    # Configuration
    SERVER_URL = "http://localhost:4999"
    ENABLE_EVENT_SIMULATION = False  # Enable/disable in-game event simulation
    ENABLE_AUDIO_PLAYBACK = True     # Enable/disable audio playback
    USE_MICROPHONE = True            # True = use microphone, False = type text
    
    print(f"\n🌐 Server URL: {SERVER_URL}")
    print(f"📊 Event simulation: {'ENABLED' if ENABLE_EVENT_SIMULATION else 'DISABLED'}")
    print(f"🔊 Audio playback: {'ENABLED' if ENABLE_AUDIO_PLAYBACK else 'DISABLED'}")
    print(f"🎤 Microphone input: {'ENABLED' if USE_MICROPHONE else 'DISABLED (text input)'}")
    
    # Initialize client
    client = GameClientSimulator(SERVER_URL)
    
    # Test server connection
    try:
        print("\n🔌 Testing server connection...")
        init_response = client.initialize()
        print(f"✓ Server responded: {init_response.get(comm_consts.KEY_REPLYTYPE)}")
    except Exception:
        print("\n❌ Could not connect to server. Please:")
        print("   1. Run Mantella in production mode (main.py)")
        print("   2. Or use VS Code: 'Mantella (Production)' debug config")
        print("   3. Wait for 'Waiting for player to select an NPC...' message")
        input("\nPress Enter to exit...")
        return
    
    # Select NPC
    selected_npc = select_npc()
    
    # Show simulated game context
    print("="*60)
    print("Simulated Game Context:")
    print("="*60)
    ps = client.game_context.PLAYER_STATE
    print(f"  Player: Level {ps['level']}, {ps['weapon']} ({'drawn' if ps['weapon_drawn'] else 'holstered'})")
    print(f"  Health: {ps['health_percent']}% | Radiation: {ps['rad_percent']}%")
    print(f"  Location: {client.game_context.LOCATION['name']}")
    print(f"  Settlement: Population {client.game_context.SETTLEMENT_CONTEXT['population']}")
    print(f"  Danger: {client.game_context.get_danger_context_string()}")
    print(f"  NPC Role: {client.game_context.get_npc_role_string(selected_npc['name'])}")
    print(f"  Nearby NPCs: {len(client.game_context.NEARBY_NPCS)}")
    for npc in client.game_context.NEARBY_NPCS[:3]:
        armed = f", armed: {npc.get('armed', npc.get('weapon', 'unarmed'))}" if 'armed' in npc or 'weapon' in npc else ""
        print(f"    - {npc['name']} ({npc['distance']} units) - {npc['faction']}{armed}")
    if len(client.game_context.NEARBY_NPCS) > 3:
        print(f"    ... and {len(client.game_context.NEARBY_NPCS) - 3} more")
    print("-"*60)
    print("Simulated MCM Settings (action permissions):")
    print(f"  allowFollow: {client.game_context.allow_follow}")
    print(f"  allowInventory: {client.game_context.allow_inventory}")
    print(f"  allowActionAggro: {client.game_context.allow_aggro}")
    print(f"  allowNPCsStayInPlace: {client.game_context.allow_npcs_stay_in_place}")
    print("-"*60)
    print("Simulated Companion Faction:")
    for npc, rank in client.game_context.companion_faction_npcs.items():
        status = f"rank {rank} (companion)" if rank >= 0 else "not companion"
        print(f"  {npc}: {status}")
    print("="*60)
    
    print("\nStarting Conversation")
    print("="*60)
    if USE_MICROPHONE:
        print("\n🎤 Speak into your microphone when prompted")
    else:
        print("\n💬 Type your responses (or 'quit' to exit)")
    print("="*60 + "\n")
    
    # Start conversation (includes full game context)
    start_response = client.start_conversation(selected_npc, use_microphone=USE_MICROPHONE)
    reply_type = start_response.get(comm_consts.KEY_REPLYTYPE)
    print(f"✓ Conversation started: {reply_type}")
    
    # Process the response like Papyrus does (check for quest IDs)
    client.process_start_response(start_response)
    if client.pending_quest_ids:
        print(f"📋 Will send quest context for {len(client.pending_quest_ids)} quests")
    
    # Base context for conversation
    base_context = {
        comm_consts.KEY_CONTEXT_LOCATION: "Sanctuary Hills",
        comm_consts.KEY_CONTEXT_TIME: 12,
        comm_consts.KEY_CONTEXT_INGAMEEVENTS: [],
        comm_consts.KEY_CONTEXT_WEATHER: "Clear",
        comm_consts.KEY_CONTEXT_CUSTOMVALUES: {}
    }
    
    turn_counter = 0
    
    try:
        while True:
            turn_counter += 1
            
            # Add events: always include action-generated events, scenario events when enabled
            current_context = base_context.copy()
            
            # Check for action-generated events (e.g., "Preston Garvey is now following")
            action_events = client.game_context.get_and_clear_action_events()
            
            # Get scenario events on certain turns (when enabled)
            scenario_events = []
            if ENABLE_EVENT_SIMULATION and turn_counter % 3 == 0:
                scenario_events = get_test_events(turn_counter, selected_npc['name'])
            
            # Combine all events
            all_events = action_events + scenario_events
            
            if action_events:
                print(f"\n🎮 GAME EVENTS from actions: {action_events}")
            if scenario_events:
                print(f"📋 SIMULATED EVENTS (turn {turn_counter}): {scenario_events}")
            
            if all_events:
                current_context[comm_consts.KEY_CONTEXT_INGAMEEVENTS] = all_events
            
            # Continue conversation (get NPC responses)
            response = client.continue_conversation(current_context)
            reply_type = response.get(comm_consts.KEY_REPLYTYPE)
            
            if reply_type == comm_consts.KEY_REPLYTYPE_NPCTALK:
                # NPC is speaking
                npc_talk = response.get(comm_consts.KEY_REPLYTYPE_NPCTALK, {})
                speaker = npc_talk.get(comm_consts.KEY_ACTOR_SPEAKER, 'NPC')
                line = npc_talk.get(comm_consts.KEY_ACTOR_LINETOSPEAK, '')
                voice_file = npc_talk.get(comm_consts.KEY_ACTOR_VOICEFILE, '')
                duration = npc_talk.get(comm_consts.KEY_ACTOR_DURATION, 0)
                
                if line:
                    print(f"\n💬 {speaker}: {line}")
                if voice_file:
                    if ENABLE_AUDIO_PLAYBACK:
                        print(f"   🎵 Playing: {Path(voice_file).name} ({duration:.1f}s)")
                        play_audio(voice_file)
                    else:
                        print(f"   🎵 Audio: {Path(voice_file).name} ({duration:.1f}s)")
                
                # Continue to get the next sentence
                
            elif reply_type == comm_consts.KEY_REPLYTYPE_PLAYERTALK:
                # Player's turn
                print("\n" + "="*60)
                
                if USE_MICROPHONE:
                    # Microphone mode: send empty string, server will listen to mic
                    print("🎤 Listening... (speak now)")
                    print("="*60)
                    player_text = ""  # Empty string triggers server-side mic listening
                else:
                    # Text mode: prompt for typed input
                    player_text = input("👤 You: ").strip()
                    print("="*60)
                    
                    if player_text.lower() in ['quit', 'exit', 'q']:
                        break
                    
                    if not player_text:
                        print("⚠️  Empty input, please type something...")
                        continue
                
                # Send player input (empty if mic, typed text if text mode)
                player_response = client.player_input(player_text, current_context)
                player_reply_type = player_response.get(comm_consts.KEY_REPLYTYPE)
                
                # Get transcribed text if using microphone
                if USE_MICROPHONE and comm_consts.KEY_TRANSCRIBE in player_response:
                    transcribed_text = player_response[comm_consts.KEY_TRANSCRIBE]
                    print(f"✓ Transcribed: {transcribed_text}\n")
                    player_text = transcribed_text  # Update player_text for potential retry
                    
                    # Check for quit command in transcribed text
                    if transcribed_text.lower().strip() in ['quit', 'exit', 'stop']:
                        print("⏹️  Quit command detected")
                        break
                
                # Check if events need updating
                if player_reply_type == comm_consts.KEY_REQUESTTYPE_TTS:
                    logging.info("Events updated, re-sending player input...")
                    player_response = client.player_input(player_text, current_context)
                    player_reply_type = player_response.get(comm_consts.KEY_REPLYTYPE)
                
                # If player voice is enabled, play it
                if player_reply_type == comm_consts.KEY_REPLYTYPE_NPCTALK:
                    player_voice = player_response.get(comm_consts.KEY_REPLYTYPE_NPCTALK, {})
                    player_voice_file = player_voice.get(comm_consts.KEY_ACTOR_VOICEFILE, '')
                    if player_voice_file:
                        if ENABLE_AUDIO_PLAYBACK:
                            print(f"🎵 Playing player voice: {Path(player_voice_file).name}")
                            play_audio(player_voice_file)
                        else:
                            print(f"🎵 Player voice: {Path(player_voice_file).name}")
                
                # Loop continues to get NPC response
                
            elif reply_type == comm_consts.KEY_REPLYTYPE_NPCACTION:
                # NPC is performing an action (no speech)
                action_data = response.get(comm_consts.KEY_REPLYTYPE_NPCACTION, {})
                actions = action_data.get(comm_consts.KEY_ACTOR_ACTIONS, [])
                if actions:
                    for action in actions:
                        action_id = action.get('identifier', 'unknown')
                        action_args = action.get('arguments', {})
                        print(f"\n🎬 ACTION: {action_id}")
                        if action_args:
                            print(f"   Args: {action_args}")
                        
                        # === SIMULATE GAME BEHAVIOR ===
                        # This mimics what MantellaConversation.psc does when processing actions
                        client.game_context.handle_action(action_id, action_args)
                
                # Continue loop to get next response (may have speech following action)
                
            elif reply_type == comm_consts.KEY_REPLYTYPE_ENDCONVERSATION:
                print("\n\n✓ Conversation ended by server")
                break
                
            else:
                print(f"\n⚠️  Unknown reply type: {reply_type}")
                # Don't break - continue loop to try getting next response
                
    except KeyboardInterrupt:
        print("\n\n⏸️  Interrupted by user")
    
    # End conversation
    print("\nEnding conversation...")
    client.end_conversation()
    print("✓ Goodbye!")


if __name__ == "__main__":
    main()
