"""
Wiki Loader - Loads pre-generated wiki content for characters.

This module loads the static wiki files generated by create_wiki_prompts.py
and provides them for injection into LLM prompts.
"""
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class WikiLoader:
    """Loads pre-generated wiki content for characters."""
    
    def __init__(self, game: str = "Fallout4"):
        """
        Args:
            game: Game name (e.g., "Fallout4", "Skyrim")
        """
        self._game = game
        self._base_path = Path(f"data/{game}/wiki/characters")
        self._cache: dict[str, str] = {}
    
    def _get_alpha_folder(self, name: str) -> str:
        """Get alphabetical folder based on last name."""
        if not name:
            return "_other"
        
        parts = name.split()
        last_part = parts[-1] if parts else name
        
        for char in last_part:
            if char.isalpha():
                return char.upper()
        
        for char in name:
            if char.isalpha():
                return char.upper()
        
        return "_other"
    
    def _sanitize_filename(self, name: str) -> str:
        """Convert character name to safe filename."""
        return name.replace(" ", "_").replace("/", "_").replace(":", "_")
    
    def get_wiki(self, character_name: str) -> str:
        """
        Load wiki content for a character.
        
        Args:
            character_name: The character's name
            
        Returns:
            Wiki content string, or empty string if not found
        """
        if not character_name:
            return ""
        
        # Check cache first
        if character_name in self._cache:
            return self._cache[character_name]
        
        # Build path
        alpha = self._get_alpha_folder(character_name)
        safe_name = self._sanitize_filename(character_name)
        wiki_path = self._base_path / alpha / f"{safe_name}.txt"
        
        # Try to load
        content = ""
        if wiki_path.exists():
            try:
                content = wiki_path.read_text(encoding='utf-8')
                logger.debug(f"Loaded wiki for {character_name} from {wiki_path}")
            except Exception as e:
                logger.warning(f"Failed to load wiki for {character_name}: {e}")
        
        # Cache result (even empty)
        self._cache[character_name] = content
        return content
    
    def get_wikis(self, character_names: list[str]) -> str:
        """
        Load wiki content for multiple characters.
        
        Args:
            character_names: List of character names
            
        Returns:
            Combined wiki content, or empty string if none found
        """
        wikis = []
        for name in character_names:
            wiki = self.get_wiki(name)
            if wiki:
                wikis.append(wiki)
        
        return "\n\n".join(wikis)
    
    def clear_cache(self):
        """Clear the wiki cache."""
        self._cache.clear()


# Singleton instance for easy access
_wiki_loader: Optional[WikiLoader] = None


def get_wiki_loader(game: str = "Fallout4") -> WikiLoader:
    """Get or create the wiki loader singleton."""
    global _wiki_loader
    if _wiki_loader is None or _wiki_loader._game != game:
        _wiki_loader = WikiLoader(game)
    return _wiki_loader


def load_character_wiki(character_name: str, game: str = "Fallout4") -> str:
    """
    Convenience function to load wiki for a character.
    
    Args:
        character_name: The character's name
        game: Game name (default: Fallout4)
        
    Returns:
        Wiki content string, or empty string if not found
    """
    return get_wiki_loader(game).get_wiki(character_name)

